const { app, BrowserWindow, ipcMain, dialog } = require('electron');
const path = require('path');
const { spawn } = require('child_process');

let mainWindow;

function createWindow() {
  mainWindow = new BrowserWindow({
    width: 900,
    height: 700,
    webPreferences: {
      preload: path.join(__dirname, 'preload.cjs'),
      nodeIntegration: false,
      contextIsolation: true,
    },
  });

  // Load the local URL in development or the local html file in production
  if (process.env.VITE_DEV_SERVER_URL) {
    mainWindow.loadURL(process.env.VITE_DEV_SERVER_URL);
    // mainWindow.webContents.openDevTools();
  } else {
    mainWindow.loadFile(path.join(__dirname, '../dist/index.html'));
  }
}

app.whenReady().then(() => {
  createWindow();

  app.on('activate', () => {
    if (BrowserWindow.getAllWindows().length === 0) {
      createWindow();
    }
  });
});

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

// IPC handler for file selection
ipcMain.handle('dialog:openFile', async () => {
  const { canceled, filePaths } = await dialog.showOpenDialog(mainWindow, {
    properties: ['openFile'],
    filters: [
      { name: 'Documents & Images', extensions: ['pdf', 'docx', 'pptx', 'xlsx', 'html', 'txt', 'csv', 'png', 'jpg', 'jpeg', 'webp', 'gif', 'bmp', 'zip'] },
      { name: 'All Files', extensions: ['*'] }
    ]
  });
  if (canceled) {
    return null;
  } else {
    return filePaths[0];
  }
});

// IPC handler for saving markdown file
ipcMain.handle('dialog:saveFile', async (event, content) => {
  const { canceled, filePath } = await dialog.showSaveDialog(mainWindow, {
    title: 'Save Markdown',
    defaultPath: 'document.md',
    filters: [{ name: 'Markdown', extensions: ['md'] }]
  });
  
  if (!canceled && filePath) {
    const fs = require('fs');
    fs.writeFileSync(filePath, content, 'utf-8');
    return filePath;
  }
  return null;
});

// IPC handler to convert file using Python script
ipcMain.handle('convert:file', async (event, filePath, apiKey, modelName, customPrompt) => {
  return new Promise((resolve, reject) => {
    try {
      const fs = require('fs');
      
      // Phase 5: Input Validation & Security (Path Traversal / Command Injection)
      if (!filePath || typeof filePath !== 'string') {
        return reject('Invalid file path provided.');
      }

      if (!fs.existsSync(filePath)) {
        return reject(`File does not exist: ${filePath}`);
      }

      const stats = fs.statSync(filePath);
      if (!stats.isFile()) {
        return reject('The provided path is not a file.');
      }

      // Phase 5: Memory / Resource Leak Protection (2GB limit)
      const MAX_FILE_SIZE_BYTES = 2 * 1024 * 1024 * 1024; // 2 GB
      if (stats.size > MAX_FILE_SIZE_BYTES) {
        return reject(`File is too large (${(stats.size / 1e9).toFixed(2)} GB). Maximum supported size is 2 GB.`);
      }

      if (stats.size === 0) {
        return reject('File is empty (0 bytes).');
      }

      const pythonExecutable = path.join(__dirname, '../python/venv/Scripts/python.exe');
      const pythonScript = path.join(__dirname, '../python/main.py');
      
      const pythonCmd = fs.existsSync(pythonExecutable) ? pythonExecutable : 'python';

      const env = { ...process.env };
      if (apiKey) {
        env['OPENAI_API_KEY'] = apiKey;
      }
      if (modelName) {
        env['PREFERRED_MODEL'] = modelName;
      }
      if (customPrompt) {
        env['CUSTOM_PROMPT'] = customPrompt;
      }

      const child = spawn(pythonCmd, [pythonScript, filePath], { env });
      
      let stdoutData = '';
      let stderrData = '';

      child.stdout.on('data', (data) => {
        try {
          // Wrap in try-catch in case we hit V8 string length limits for massive outputs
          stdoutData += data.toString('utf-8');
        } catch (e) {
          child.kill();
          reject('Output generated by conversion exceeded Node.js memory limits.');
        }
      });

      child.stderr.on('data', (data) => {
        stderrData += data.toString('utf-8');
      });

      child.on('close', (code) => {
        if (code !== 0) {
          reject(stderrData || 'Unknown error occurred during conversion');
        } else {
          resolve(stdoutData);
        }
      });

      child.on('error', (err) => {
        reject(`Failed to start conversion process: ${err.message}`);
      });

    } catch (e) {
      reject(`Unexpected internal error: ${e.message}`);
    }
  });
});
